package com.example.secondapplication

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController

@Composable
fun FirstScreen(navController: NavController) {

    var inputText by remember { mutableStateOf("") }
    var isListGenerated by remember { mutableStateOf(false) }
    val isNumEntered = inputText.toIntOrNull()?.let { it in 1..20 } == true


    Column(modifier = Modifier.padding(start = 60.dp, top = 350.dp)) {

        OutlinedTextField(
            value = inputText,
            onValueChange = {
                inputText = it
                isListGenerated = false
                DataRepository.clearList()
            },
            label = { Text(
                text = "Введите число от 1 до 20",
                fontSize = 20.sp
            ) },
            modifier = Modifier
                .height(70.dp)
                .width(290.dp)
        )

        Spacer(modifier = Modifier.height(10.dp))

        Button(
            onClick = {
                val cnt = inputText.toInt()
                DataRepository.generateListOfSongs(cnt)
                isListGenerated = true

            },
            enabled = isNumEntered,
            modifier = Modifier
                .height(70.dp)
                .width(290.dp)
        ) {
            Text(
                text = "Жми сюда",
                fontSize = 20.sp
            )
        }

        Spacer(modifier = Modifier.height(10.dp))

        Button(
            onClick = {
                navController.navigate("second_screen")
            },
            enabled = isListGenerated,
            modifier = Modifier
                .height(70.dp)
                .width(290.dp),
        ) {
            Text(
                text = "Теперь сюда",
                fontSize = 20.sp
            )
        }
    }
}